// generated by blockdb@0.4.0 — do not edit
export interface Addresses {
  key: string;
  number: string;
  street: string;
  state: string;
  city?: string;
  unit?: string;
  postcode?: string;
}

export interface Records {
  addresses: Addresses;
}

export const schema = {
  addresses: {
    fields: {
      key: { kind: "string", operators: ["equals", "in", "gt", "gte", "lt", "lte", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "gt", "gte", "lt", "lte", "startsWith"] },
      number: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      street: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      state: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      city: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith"], absent: true },
      unit: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      postcode: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith"], absent: true },
    },
  },
} as const;

export type Schema = typeof schema;
