// generated by blockdb@0.2.1 — do not edit
export interface Addresses {
  number: string;
  street: string;
  state: string;
  city?: string;
  unit?: string;
  postcode?: string;
}

export interface Records {
  addresses: Addresses;
}

export const schema = {
  addresses: {
    fields: {
      number: { kind: "string", operators: ["equals", "in", "startsWith", "not"] },
      street: { kind: "string", operators: ["equals", "in", "gt", "gte", "lt", "lte", "startsWith", "not"] },
      state: { kind: "string", operators: ["equals", "in", "startsWith", "not"] },
      city: { kind: "string", operators: ["equals", "in", "startsWith", "not", "isAbsent", "exists"], absent: true },
      postcode: { kind: "string", operators: ["equals", "in", "startsWith", "not", "isAbsent", "exists"], absent: true },
    },
  },
} as const;

export type Schema = typeof schema;
